export const GET_COMICS = 'GET_COMICS';
export const GET_COMIC = 'GET_COMIC';
export const GET_COMIC_CHARACTERS = 'GET_COMIC_CHARACTERS';
export const GET_COMIC_CREATORS = 'GET_COMIC_CREATORS';
export const GET_COMIC_EVENTS = 'GET_COMIC_EVENTS';
export const GET_COMIC_STORIES = 'GET_COMIC_STORIES';